version: '3.8'

services:
  db:
    image: postgres:alpine  # Образ PostgreSQL
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookings_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохранение данных между перезапусками

  app:
    build: .
    container_name: booking_service
    restart: always
    depends_on:
      - db  # FastAPI запустится после PostgreSQL
    environment:
      DATABASE_URL: postgresql://myuser:password@db:5432/bookings_database
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Монтируем код внутрь контейнера

volumes:
  postgres_data:  # Персистентное хранилище для базы данных
